#!/bin/bash
a=$( git status | grep "Untracked" )
b=$( git status | grep "Changes not staged" )
c=$( git status | grep "Changes to be" )
if [ "$a" != "" ] || [ "$b" != "" ] || [ "$c" != "" ]
then
	git add .
	read -p 'Insert the comment for the update ' comment
	git commit -m $comment
	git push
fi
