#!/bin/bash
./update
a=$( git status | grep "Untracked" )
b=$( git status | grep "Changes not staged" )
c=$( git status | grep "Changes to be" )
if [ "$a" != "" ]
then
	git add .
	read -p 'Insert the comment for the update ' comment
	git commit -m $comment
	git push
fi
if [ "$c" != "" ]
then
	echo 2
fi
if [ "$b" != "" ]
then
	echo 3
fi
