function y = cubic(f,alpha,T,N)
%cubic Summary of this function goes here
%   Integral de Riemann-Liouville entre 0 y T   
    h=T/(3*N);
    sum = 0;
    
    for i=0:N-1
       D=((3^alpha)*(h^alpha))*((2*((N-i-1)^(alpha+1))*(alpha^2 ...
           +alpha*(-4-9*i+9*N)+3*(1+3*i-3*N)*(2+3*i-3*N)))...
           +(((N-i)^alpha)*(2*alpha^3+(alpha^2)*(12+11*i-11*N)...
           +alpha*(22+36*(i-N)^2+55*(i-N))...
           +6*(1+3*i-3*N)*(2+3*i-3*N)*(1+i-N))));
       E=((3^(alpha+2))*(h^alpha))*(((2*(N-i)^(alpha+1))*(alpha^2 ...
           +5*alpha*(1+i-N)+3*(2+3*i-3*N)*(1+i-N)))...
           -(((N-i-1)^(alpha+1))*(alpha^2+alpha*(-3-8*i+8*N)...
           +6*(2+3*i-3*N)*(i-N))));
       F=((3^(alpha+2))*(h^alpha))*(((2*(N-i-1)^(alpha+1))*(alpha^2 ...
           +5*alpha*(N-i)+3*(1+3*i-3*N)*(i-N)))...
           -(((N-i)^(alpha+1))*(alpha^2+alpha*(5+8*i-8*N)...
           +6*(1+3*i-3*N)*(1+i-N))));
       G=((3^alpha)*(h^alpha))*(((2*(N-i)^(alpha+1))*(alpha^2 ...
           +alpha*(5+9*i-9*N)+3*(1+3*i-3*N)*(2+3*i-3*N)))...
           -(((N-i-1)^alpha)*(2*alpha^3+(alpha^2)*(1-11*i+11*N)...
           +alpha*(3+36*(i-N)^2+17*(i-N))...
           -6*(1+3*i-3*N)*(2+3*i-3*N)*(i-N))));
       sum = sum + D*f((3*i)*h) + E*f((3*i+1)*h) + F*f((3*i+2)*h)...
           + G*f((3*i+3)*h);
    end
    y = sum;
    y = y/(2*gamma(alpha+4));
end

